### ISSUE TITLE
About Error in training disconet，please

### ISSUE THREAD

**Issue by lzh594** [huiyegit/UAV3D#10]
Dear Authors:

Your outstanding work truly promote UAV-related research. But I encountered some difficulties in the process of reproducing it, and I really hope you can help me，thanks！

When I tried to train disconet, I encountered the following error：

> Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 87, in main
    if model.com_type == "DiscoNet":
  File "/home/user/miniconda3/envs/bevfusion/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'BEVFusion' object has no attribute 'com_type'

Error code：
``` python
# UAV3D/collaborative_perception/bevfusion/tools/train.py
if model.com_type == "DiscoNet":
    resume_teacher = 'runs/upperbound/epoch_24.pth'
    checkpoint_teacher = torch.load(resume_teacher)
    model.teacher.load_state_dict(checkpoint_teacher["state_dict"])
    print("Load teacher model")
    model.teacher.eval()
```
The training command I tried is as follows:
``` bash
torchpack dist-run -np 2 python tools/train.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/disconet/default.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --run-dir runs/disconet
```
I have tried to fix this error but to no avail. 

Thanks again, looking forward to your reply！

**Comment by huiyegit** [comment]
The definition of BEVFusion is here : https://github.com/huiyegit/UAV3D/blob/main/collaborative_perception/bevfusion/mmdet3d/models/fusion_models/bevfusion.py

You may need to set up and compile the environment in the specified folder:  ./collaborative_perception/bevfusion/

**Comment by nobub** [comment]
@lzh594 hello, have you solved this issue? i have found the same question.
